// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'header-level': string;
  'header-level-1': string;
  'header-level-2': string;
  'header-level-3': string;
  'selected': string;
}
export const cssExports: CssExports;
export default cssExports;
