// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'auth-button': string;
  'login-button': string;
}
export const cssExports: CssExports;
export default cssExports;
