// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'mm-tables-container': string;
  'mmresult': string;
}
export const cssExports: CssExports;
export default cssExports;
